import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {collection,doc,onSnapshot,setDoc,updateDoc} from 'firebase/firestore';
import {db,ensureAuth,firebaseReady} from './firebase';
import questions from './questions';
import './styles.css';

const newCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const pick=()=>questions[Math.floor(Math.random()*questions.length)];
const params=new URLSearchParams(location.search); const initialRoom=params.get('room');

function App(){
 const [room,setRoom]=useState(initialRoom||''); const [name,setName]=useState(''); const [me,setMe]=useState(null); const [data,setData]=useState(null); const [view,setView]=useState(initialRoom?'join':'home'); const [error,setError]=useState('');
 const ready=useMemo(()=>firebaseReady,[firebaseReady]);
 useEffect(()=>{ if(!room||!ready)return; let unsub; (async()=>{try{await ensureAuth(); unsub=onSnapshot(doc(db,'rooms',room),s=>setData(s.exists()?s.data():null),e=>setError(e.message));}catch(e){setError(e.message)}})(); return()=>unsub?.()},[room,ready]);
 const create=async()=>{setError('');if(!ready){setError('أكملي إعداد Firebase أولًا من ملف .env.local');return} if(!name.trim()){setError('اكتبي اسمك الأول');return} const code=newCode(); await ensureAuth(); await setDoc(doc(db,'rooms',code),{createdAt:Date.now(),playerA:{name:name.trim(),question:pick(),count:0},playerB:null,status:'waiting'}); setRoom(code); setMe('A'); history.replaceState({},'',`?room=${code}`);setView('game')};
 const join=async()=>{setError('');if(!ready){setError('إعداد Firebase ناقص');return}if(!name.trim()){setError('اكتبي اسمك الأول');return}if(!room){setError('رابط الغرفة غير موجود');return} await ensureAuth(); const ref=doc(db,'rooms',room); const p=data?.playerB; if(p){setError('الغرفة ممتلئة بالفعل');return} await updateDoc(ref,{playerB:{name:name.trim(),question:pick(),count:0},status:'playing'});setMe('B');setView('game')};
 const chooseMe=()=>{if(data?.playerA?.name===name) return 'A'; if(data?.playerB?.name===name)return 'B'; return me};
 if(!ready) return <div className="app"><div className="shell"><div className="top"><div><h1 className="brand">مَشَاعِر</h1><div className="sub">لعبة لشخصين — Dark Romance</div></div></div><div className="card hero"><h2>جاهزين؟</h2><p>المشروع جاهز محليًا، لكن اللعب بين جهازين يحتاج Firebase لمزامنة الغرف لحظيًا. ضعي مفاتيح Firebase في <b>.env.local</b> ثم شغّلي الموقع.</p><div className="notice">اقرئي ملف <b>SETUP.md</b> داخل المشروع؛ الإعداد مرة واحدة فقط.</div></div></div></div>;
 if(view==='home')return <Home name={name} setName={setName} create={create} error={error}/>;
 if(view==='join')return <Join room={room} name={name} setName={setName} join={join} error={error} data={data}/>;
 return <Game data={data} room={room} me={chooseMe()} name={name} setData={setData} error={error}/>;
}
function Home({name,setName,create,error}){return <div className="app"><div className="shell"><div className="top"><div><h1 className="brand">مَشَاعِر</h1><div className="sub">مش كل حاجة بنحسها… بنعرف نقولها.</div></div><span className="pill">1000+ سؤال</span></div><div className="card hero"><h1>اتكلموا أكتر.</h1><p>غرفة خاصة ليكي ولخطيبك. كل واحد بياخد سؤال عشوائي مستقل، واللعبة بس بتزامن الأدوار بينكم.</p><input className="field" placeholder="اسمك" value={name} onChange={e=>setName(e.target.value)}/><br/><br/><button className="btn" onClick={create}>إنشاء غرفة</button>{error&&<p className="error">{error}</p>}</div><div className="footer">Burgundy · Dark Mode · أسئلة مستقلة · رابط مشاركة</div></div></div>}
function Join({room,name,setName,join,error,data}){return <div className="app"><div className="shell"><div className="top"><div><h1 className="brand">مَشَاعِر</h1><div className="sub">اتدعيتِ لغرفة خاصة</div></div><span className="pill">#{room}</span></div><div className="card center"><h2>انضمي للغرفة</h2><p className="sub">{data?.playerA?.name?`الغرفة بدأت بواسطة ${data.playerA.name}`:'جارٍ تحميل الغرفة…'}</p><input className="field" placeholder="اسمك" value={name} onChange={e=>setName(e.target.value)}/><br/><br/><button className="btn" onClick={join}>دخول اللعبة</button>{error&&<p className="error">{error}</p>}</div></div></div>}
function Game({data,room,me,name,error}){if(!data)return <div className="app"><div className="shell"><div className="card center"><h2>الغرفة غير موجودة</h2><p>تأكدي من الرابط أو أنشئي غرفة جديدة.</p></div></div></div>; const player=data[me==='A'?'playerA':'playerB']; const other=data[me==='A'?'playerB':'playerA']; const next=async()=>{const key=me==='A'?'playerA':'playerB';const q=pick();await updateDoc(doc(db,'rooms',room),{[key]:{...player,question:q,count:(player.count||0)+1}})}; const copy=()=>navigator.clipboard.writeText(location.href); return <div className="app"><div className="shell"><div className="top"><div><h1 className="brand">مَشَاعِر</h1><div className="sub">{player?.name} — دورك</div></div><button className="btn secondary" onClick={copy}>نسخ رابط الدعوة</button></div><div className="card"><div className="meta"><span>{player?.count||0} سؤال</span><span>{other?'🟢 '+other.name+' متصل':'⏳ مستني الشخص التاني'}</span></div><div className="progress"><i style={{width:`${Math.min(((player?.count||0)%20)*5+5,100)}%`}}/></div><div className="pill">{player?.question?.category} · مستوى {player?.question?.level}</div><div className="question">{player?.question?.text}</div><div className="row"><button className="btn" onClick={next}>سؤال جديد ↻</button><button className="btn ghost" onClick={next}>مش عايز أجاوب</button></div><div className="divider"/><div className="notice">كل لاعب له سؤال مستقل تمامًا. تغيير سؤالك لا يغيّر سؤال الطرف الثاني.</div>{error&&<p className="error">{error}</p>}</div><div className="footer">غرفة #{room} · لا يوجد ترتيب بينكم، الهدف الكلام مش الفوز.</div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
